syntax = "proto3";

import "com/eblan/launcher/data/datastore/proto/general/theme.proto";
import "com/eblan/launcher/data/datastore/proto/general/icon_tint.proto";
import "com/eblan/launcher/data/datastore/proto/general/icon_shape.proto";

option java_package = "com.eblan.launcher.data.datastore.proto.general";
option java_multiple_files = true;

message GeneralSettingsProto {
  optional ThemeProto themeProto = 1;
  optional bool dynamicTheme = 3;
  optional string iconPackPackageName = 4;
  optional IconTintProto iconTintProto = 5;
  optional int32 customIconTint = 6;
  optional bool fallbackIconTint = 7;
  optional IconShapeProto iconShapeProto = 8;
}